<%@ Page Language="VB" MasterPageFile="~/Forms/Plantilla.master" AutoEventWireup="false" CodeFile="departamento.aspx.vb" Inherits="Forms_departamento" title="Departamento" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <p align=center>Departamentos</p>
            
            <p align="center">
                Codigo&nbsp;<asp:TextBox ID="TextBox1" runat="server" 
                    CssClass="Alinear_Objetos" Height="22px" MaxLength="20"></asp:TextBox>
                <asp:Label ID="Label1" runat="server"></asp:Label>
            </p>
            <p align="center">
                Nombre
                </p>
                <asp:TextBox ID="TextBox2" runat="server" CssClass="Alinear_Objetos" 
                MaxLength="100"></asp:TextBox>
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:ImageButton ID="btnnuevo" runat="server" Height="49px" 
                ImageUrl="~/imagenes/nuevo.png" Width="56px" 
                ToolTip="Habilitar y Limpiar Campos." />
            <asp:ImageButton ID="btnguardar" runat="server" Height="49px" 
                ImageUrl="~/imagenes/guardar.png" Width="56px" 
                ToolTip="Guardar los valores." />
            <asp:ImageButton ID="btncancelar" runat="server" 
                ImageUrl="~/imagenes/Cancel.png" />
            <br />
            <asp:Button ID="btnconsultodos" runat="server" BorderStyle="Solid" 
                CssClass="Alinear_Objetos" Font-Size="XX-Small" Height="18px" 
                Text="Consultar Todos" Width="87px" />
            <p align=center><asp:TextBox ID="txtbus" runat="server"></asp:TextBox>
                <asp:ImageButton ID="btnbuscar" runat="server" Height="31px" 
                    ImageUrl="~/imagenes/buscar.png" Width="33px" ToolTip="Buscar(id y Nombre)" /></p>
            <p align=center>
                <asp:Label ID="Label2" runat="server"></asp:Label>
            </p>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" AllowPaging="True" 
                CssClass="Alinear_GridVief" BackColor="White" BorderColor="#3366CC" 
                BorderStyle="None" BorderWidth="1px" CellPadding="4">
                <RowStyle BackColor="White" ForeColor="#003399" />
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            </asp:GridView>
            <asp:HiddenField ID="accion" runat="server" />
            <asp:ScriptManager ID="ScriptManager1" runat="server">
            </asp:ScriptManager>
            <br />
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>

