<%@ Page Language="VB" MasterPageFile="~/Forms/Plantilla.master" AutoEventWireup="false" CodeFile="Empleado.aspx.vb" Inherits="Forms_Empleado" title="Empleado" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
    <ContentTemplate>
        <p align=center><b>EMPLEADO</b></p>
        <p align=center>Cedula
        <asp:TextBox ID="TextBox1" runat="server" CssClass="Alinear_Objetos" MaxLength="50"></asp:TextBox>
            <asp:Label ID="Label1" runat="server"></asp:Label>
        </p>
        <p align="center">
            Nombre</p>
        <asp:TextBox ID="txtnom" runat="server" Height="21px" 
            CssClass="Alinear_Objetos" Width="129px" MaxLength="50"></asp:TextBox>
        <p align=center>Apellido<asp:TextBox ID="TextBox3" runat="server" 
                CssClass="Alinear_Objetos" Height="21px" Width="129px" MaxLength="50"></asp:TextBox>
        </p>
        <p align="center">
            Direccion<asp:TextBox ID="TextBox4" runat="server" CssClass="Alinear_Objetos" 
                Height="21px" Width="198px" MaxLength="50"></asp:TextBox>
        </p>
        <p align="center">
            Telefono<asp:TextBox ID="TextBox5" runat="server" CssClass="Alinear_Objetos" 
                Height="21px" Width="129px" MaxLength="50"></asp:TextBox>
        </p>
        <p align="center">
            Email<asp:TextBox ID="TextBox6" runat="server" CssClass="Alinear_Objetos" 
                Height="21px" Width="188px" MaxLength="100"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                ControlToValidate="TextBox6" ErrorMessage="Direccion Invalida" 
                ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
        </p>
        <p align="center">
            Cargo</p>
        <asp:DropDownList ID="cbcar" runat="server" CssClass="Alinear_Objetos">
        </asp:DropDownList>
        <br />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:ImageButton ID="btnnuevo" runat="server" Height="49px" 
            ImageUrl="~/imagenes/nuevo.png" Width="56px" 
            ToolTip="Habilitar los campos" />
        <asp:ImageButton ID="btnguardar" runat="server" 
            ImageUrl="~/imagenes/guardar.png" Height="49px" Width="56px" 
            ToolTip="Guardar los datos" />
        <asp:ImageButton ID="btncancelar" runat="server" 
            ImageUrl="~/imagenes/Cancel.png" onclientclick="return confirm('¿Esta Seguro de Salir del Formulario?');" />
        <br />
        <asp:Button ID="btnconsultodos" runat="server" BorderStyle="Solid" 
            CssClass="Alinear_Objetos" Font-Size="XX-Small" Height="18px" 
            Text="Consultar Todos" Width="87px" />
        <p align=center><asp:TextBox ID="txtbus" runat="server"></asp:TextBox>
                <asp:ImageButton ID="btnbuscar" runat="server" Height="31px" 
                    ImageUrl="~/imagenes/buscar.png" Width="33px" ToolTip="Buscar(id y Nombre)" /></p>
        <p align=center><asp:Label ID="Label2" runat="server"></asp:Label></p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" AllowPaging="True" style="margin-right: 2px; top: 0px; left: -105px;" BackColor="White" 
                                                                BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                                                                CssClass="Alinear_GridVief" >
                                                                 <RowStyle BackColor="White" ForeColor="#003399" />
                                                                 <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                                                                 <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                                                                 <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                                                                 <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
        </asp:GridView>
        <br />
        <asp:HiddenField ID="accion" runat="server" />
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <br />
    </ContentTemplate>
</asp:UpdatePanel>
    
</asp:Content>

