<%@ Page Language="VB" MasterPageFile="~/Forms/Plantilla.master" AutoEventWireup="false" CodeFile="Productos.aspx.vb" Inherits="Forms_Productos" title="Productos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<script language="javascript" type="text/javascript">
 
function AcceptNum(evt) {
              var keynum;
            if (window.event) // IE
            {
                keynum = evt.keyCode;
            }
            else if (evt.which) // Netscape/Firefox/Opera
            {
                keynum = evt.which;
            }
            return (keynum < 13 || (keynum >= 48 && keynum <= 57))       
          }

 
 </script>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <p align=center><b>PRODUCTOS</b></p>
                <p align="center">
                    Codigo</p>
                <asp:TextBox ID="TextBox1" runat="server" CssClass="Alinear_Objetos" 
                    ToolTip="Recuerde que este campo lo genera el Sistema"></asp:TextBox>
                    <p align=center><asp:Label ID="Label1" runat="server"></asp:Label></p>
                    <p align="center">
                    Referencia</p>
                <asp:TextBox ID="TextBox5" runat="server" CssClass="Alinear_Objetos" 
                    ToolTip="Recuerde que este campo es Numérico" MaxLength="50"></asp:TextBox>
                <p align=center>Nombre</p>
                <asp:TextBox ID="TextBox2" runat="server" CssClass="Alinear_Objetos" 
                    MaxLength="50"></asp:TextBox>
                <p align=center>Valor</p>
                <asp:TextBox ID="TextBox3" runat="server" CssClass="Alinear_Objetos" 
                    ToolTip="Recuerde que este campo es  Numérico"></asp:TextBox>
                <p align=center>Descripción</p>
                <asp:TextBox ID="TextBox4" runat="server" CssClass="Alinear_Objetos" 
                    Height="61px" MaxLength="100" TextMode="MultiLine" Width="216px"></asp:TextBox>
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:ImageButton ID="btnuevo" runat="server" Height="49px" 
                    ImageUrl="~/imagenes/nuevo.png" Width="56px" ToolTip="Habilitar Campos" />
                <asp:ImageButton ID="btnguardar" runat="server" 
                    ImageUrl="~/imagenes/guardar.png" Height="49px" Width="56px" 
                    ToolTip="Guardar Datos" />
                <asp:ImageButton ID="btncancelar" runat="server" 
                    ImageUrl="~/imagenes/Cancel.png" 
                    onclientclick="return confirm('¿Esta Seguro de Salir del Formulario?');" />
                <p align=center><asp:TextBox ID="txtbus" runat="server"></asp:TextBox>
                <asp:ImageButton ID="btnbuscar" runat="server" Height="31px" 
                    ImageUrl="~/imagenes/buscar.png" Width="33px" ToolTip="Buscar(id y Nombre)" />&nbsp;</p>
                <asp:Button ID="btnconsultodos" runat="server" BorderStyle="Solid" 
                    Font-Size="XX-Small" Height="18px" Text="Consultar Todos" Width="87px" 
                    CssClass="Alinear_Objetos" />
                <p align=center>
                    <asp:Label ID="Label2" runat="server"></asp:Label>
                    <br />
                </p>
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateEditButton="True" 
                    CssClass="Alinear_GridVief" AlternatingRowStyle-CssClass="alt"  
                    BackColor="White" BorderColor="#3366CC" 
                    BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="codigo" 
                    AutoGenerateDeleteButton="True">
                    <RowStyle BackColor="White" ForeColor="#003399" />
                    <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                    <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                    <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                    <AlternatingRowStyle CssClass="alt" />
                </asp:GridView>
                <asp:ScriptManager ID="ScriptManager1" runat="server">
                </asp:ScriptManager>
                <asp:HiddenField ID="accion" runat="server" />
                <br />
                <br />
            </ContentTemplate>
        </asp:UpdatePanel>
</asp:Content>

